### ISSUE TITLE
Add coverage to sub-second average block time

### ISSUE THREAD

**Issue by TomasCImach** [overlay-market/v1-core#170]
Suggestion -> change risk param [14] AverageBlockTime to be on miliseconds instead of seconds.

**Comment by magnetto90** [comment]
https://github.com/overlay-market/v1-core/blob/main/contracts/OverlayV1Market.sol#L619-L648

This is the only part of the code that uses the average block time. Do Chainlink feeds uses the `hasReserve` return value?

**Comment by magnetto90** [comment]
@TomasCImach seeing Arbiscan there are at least 4 blocks per second but the timestamp is the same for each of them. What I mean is that the timestamp change at most once per second.

**Comment by TomasCImach** [comment]
https://github.com/overlay-market/v1-core/pull/171
