### ISSUE TITLE
Update OverlayV1Market Events

### ISSUE THREAD

**Issue by bigboydiamonds** [overlay-market/v1-core#56]
Currently there is no event for our v1 subgraphs to update per market data (price points, oi, funding rate, etc). 

Proposing adding an event emitted to allow for subgraphs to index `Oracle.Data` when `OverlayV1Market.update()` is called.

**Comment by mikeyrf** [comment]
This would be good for emitting oiLong and oiShort. For oracle prices from Oracle.Data, update() won't be called as frequently as the actual price from the oracle changes, so we may want to use existing Uni V3 subgraphs for that?

**Comment by bigboydiamonds** [comment]
<img width="661" alt="Screen Shot 2022-04-21 at 12 29 38 PM" src="https://user-images.githubusercontent.com/57741810/164538462-02ddee48-d1ca-43ac-806e-3d1a1b6eb249.png">

Proposing to add an argument ```address market``` to be emitted in the ```Build``` event. This way our subgraphs can utilize the market contract address to make additional queries for position related updates on ```Liquidate``` or ```Unwind```.

**Comment by bigboydiamonds** [comment]
<img width="632" alt="Screen Shot 2022-04-22 at 9 45 45 AM" src="https://user-images.githubusercontent.com/57741810/164758485-5a70807c-eab0-47a2-b017-a229224c42d1.png">

When updating per market parameters listening to the ```ParamUpdated``` event, it would be helpful to have the array index of the specific parameter being updated. Proposing to add an additional argument ```index```, returning the array index within ```params``` on OverlayV1Market, to event ```ParamUpdated```

**Comment by mikeyrf** [comment]
Sorry might be a bit confusing. The `name` param is the index to use.

Also for `Build`, not sure I understand why you need the market contract address there?
